[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "argon2-cffi>=25.1.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]
